# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: cd
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

permissions:
  checks: read
  contents: write

jobs:
  dump:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump event payload
        run: |
          jq . "$GITHUB_EVENT_PATH"
      - name: Dump status
        run: |
          jq -r .check_run.status < $GITHUB_EVENT_PATH
      - name: Dump name
        run: |
          $NAME
  maven-cd:
    uses: ./.github/workflows/maven-cd.yml
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
