name: verify-ci-status
description: Verifies that a CI status is passing before proceeding.
inputs:
  GITHUB_TOKEN:
    description: Token to run with, defaults to the repository GITHUB_TOKEN
    required: true
  output_result:
    description: Outputs the result as 'result = success' if check is passed or an error result if not
    required: false
  name:
    required: false
    description: Name of the check to validate against
    default: Jenkins
outputs:
  result:
    value: ${{ steps.verify-ci-status.outputs.result }}
    description: success if the check succeeded otherwise a message describing the result
runs:
  using: composite
  steps:
    - name: Dump event payload
      run: |
        jq . "$GITHUB_EVENT_PATH"
    - run: $GITHUB_ACTION_PATH/run.sh
      id: verify-ci-status
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NAME: ${{ inputs.name }}
        OUTPUT_RESULT: ${{ inputs.output_result }}
